curCellX=(obj_player.x div global.idealWidth)
curCellY=(obj_player.y div global.idealHeight)
var wallLay_id = layer_get_id("Wall");
var wallMap_id = layer_tilemap_get_id(wallLay_id);
global.roomSlotUsed=true

if(global.roomLocked=false){
	global.roomLocked=true
	if(global.gridRooms[curCellX,curCellY].doorRight){
		if(curCellX<3){
			if(global.gridPath[curCellX+1,curCellY]!="F"&&global.gridPath[curCellX,curCellY]!="S"){
				if(global.gridPath[curCellX+1,curCellY]=="S"||global.gridPath[curCellX,curCellY]=="F"){
					doorSpawnX=((global.idealWidth*curCellX)+(global.idealWidth-32))
					doorSpawnY=((global.idealHeight*curCellY)+(11*32))
					instance_create_layer(doorSpawnX,doorSpawnY,"Instances",obj_vDoor)
					tilemap_set(wallMap_id,8,32+(32*curCellX),12+(24*curCellY))
					tilemap_set(wallMap_id,8,32+(32*curCellX),13+(24*curCellY))
					tilemap_set(wallMap_id,8,31+(32*curCellX),12+(24*curCellY))
					tilemap_set(wallMap_id,8,31+(32*curCellX),13+(24*curCellY))
				}else{
					if(global.gridPath[curCellX+1,curCellY]<global.gridPath[curCellX,curCellY]){
						doorSpawnX=((global.idealWidth*curCellX)+(global.idealWidth-32))
						doorSpawnY=((global.idealHeight*curCellY)+(11*32))
						instance_create_layer(doorSpawnX,doorSpawnY,"Instances",obj_vDoor)
						tilemap_set(wallMap_id,8,32+(32*curCellX),12+(24*curCellY))
						tilemap_set(wallMap_id,8,32+(32*curCellX),13+(24*curCellY))
						tilemap_set(wallMap_id,8,31+(32*curCellX),12+(24*curCellY))
						tilemap_set(wallMap_id,8,31+(32*curCellX),13+(24*curCellY))
					}
				}
			}
		}
	}
	if(global.gridRooms[curCellX,curCellY].doorBottom){
		if(curCellY<3){
			if(global.gridPath[curCellX,curCellY+1]!="F"&&global.gridPath[curCellX,curCellY]!="S"){
				if(global.gridPath[curCellX,curCellY+1]=="S"||global.gridPath[curCellX,curCellY]=="F"){
					doorSpawnX=((global.idealWidth*curCellX)+(15*32))
					doorSpawnY=((global.idealHeight*curCellY)+(global.idealHeight-32))
					instance_create_layer(doorSpawnX,doorSpawnY,"Instances",obj_hDoor)
					tilemap_set(wallMap_id,8,15+(32*curCellX),23+(24*curCellY))
					tilemap_set(wallMap_id,8,16+(32*curCellX),23+(24*curCellY))
					tilemap_set(wallMap_id,8,15+(32*curCellX),24+(24*curCellY))
					tilemap_set(wallMap_id,8,16+(32*curCellX),24+(24*curCellY))
				}else{
					if(global.gridPath[curCellX,curCellY+1]<global.gridPath[curCellX,curCellY]){
						doorSpawnX=((global.idealWidth*curCellX)+(15*32))
						doorSpawnY=((global.idealHeight*curCellY)+(global.idealHeight-32))
						tilemap_set(wallMap_id,8,15+(32*curCellX),23+(24*curCellY))
						tilemap_set(wallMap_id,8,16+(32*curCellX),23+(24*curCellY))
						tilemap_set(wallMap_id,8,15+(32*curCellX),24+(24*curCellY))
						tilemap_set(wallMap_id,8,16+(32*curCellX),24+(24*curCellY))
						instance_create_layer(doorSpawnX,doorSpawnY,"Instances",obj_hDoor)
					}
				}
			}
		}
	}
	if(global.gridRooms[curCellX,curCellY].doorLeft){
		if(curCellX>0){
			if(global.gridPath[curCellX-1,curCellY]!="F"&&global.gridPath[curCellX,curCellY]!="S"){
				if(global.gridPath[curCellX-1,curCellY]=="S"||global.gridPath[curCellX,curCellY]=="F"){
					doorSpawnX=((global.idealWidth*curCellX))
					doorSpawnY=((global.idealHeight*curCellY)+(11*32))
					instance_create_layer(doorSpawnX,doorSpawnY,"Instances",obj_vDoor)
					tilemap_set(wallMap_id,8,(32*curCellX),12+(24*curCellY))
					tilemap_set(wallMap_id,8,(32*curCellX),13+(24*curCellY))
					tilemap_set(wallMap_id,8,(32*curCellX)-1,12+(24*curCellY))
					tilemap_set(wallMap_id,8,(32*curCellX)-1,13+(24*curCellY))
				}else{
					if(global.gridPath[curCellX-1,curCellY]<global.gridPath[curCellX,curCellY]){
						doorSpawnX=((global.idealWidth*curCellX))
						doorSpawnY=((global.idealHeight*curCellY)+(11*32))
						instance_create_layer(doorSpawnX,doorSpawnY,"Instances",obj_vDoor)
						tilemap_set(wallMap_id,8,(32*curCellX),12+(24*curCellY))
						tilemap_set(wallMap_id,8,(32*curCellX),13+(24*curCellY))
						tilemap_set(wallMap_id,8,(32*curCellX)-1,12+(24*curCellY))
						tilemap_set(wallMap_id,8,(32*curCellX)-1,13+(24*curCellY))
					}
				}
			}
		}
	}
	if(global.gridRooms[curCellX,curCellY].doorTop){
		if(curCellY>0){
			if(global.gridPath[curCellX,curCellY-1]!="F"&&global.gridPath[curCellX,curCellY]!="S"){
				if(global.gridPath[curCellX,curCellY-1]=="S"||global.gridPath[curCellX,curCellY]=="F"){
					doorSpawnX=((global.idealWidth*curCellX)+(15*32))
					doorSpawnY=((global.idealHeight*curCellY)+(32))
					instance_create_layer(doorSpawnX,doorSpawnY,"Instances",obj_hDoor)
					tilemap_set(wallMap_id,8,15+(32*curCellX),1+(24*curCellY))
					tilemap_set(wallMap_id,8,16+(32*curCellX),1+(24*curCellY))
					tilemap_set(wallMap_id,8,15+(32*curCellX),(24*curCellY))
					tilemap_set(wallMap_id,8,16+(32*curCellX),(24*curCellY))
				}else{
					if(global.gridPath[curCellX,curCellY-1]<global.gridPath[curCellX,curCellY]){
						doorSpawnX=((global.idealWidth*curCellX)+(15*32))
						doorSpawnY=((global.idealHeight*curCellY)+(32))
						instance_create_layer(doorSpawnX,doorSpawnY,"Instances",obj_hDoor)
						tilemap_set(wallMap_id,8,15+(32*curCellX),1+(24*curCellY))
						tilemap_set(wallMap_id,8,16+(32*curCellX),1+(24*curCellY))
						tilemap_set(wallMap_id,8,15+(32*curCellX),(24*curCellY))
						tilemap_set(wallMap_id,8,16+(32*curCellX),(24*curCellY))
					}
				}
			}
		}
	}
}